### ISSUE TITLE
User Story:Search/Select different destinations

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/Escape-and-explore#1]
**User story:**
As a website user, I would like to be able to select or search for different cities so I can choose my next holiday destination

**Acceptance criteria**
-  [x]  A user must be able to search for or select different cities

**Tasks**
- [x] Display separate images of different cities
- [x] Make each image selectable
- [x] Add a name for each city, image and name will be placed in a card format
