### ISSUE TITLE
User Story:User location and map marker

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/Escape-and-explore#10]
**User Story:**
As a user, I would like to be able to see both where I am and where my potential destination is
at the same time

**Acceptance Criteria**
- [x] The users location must be pinned on the map, ideally users pin is a different color to holiday destination pin
- [ ] Create a button for the user to direct the map to their location if location permissions has been enabled

**Tasks**
- [x] Display a marker on the users location if permissions are given
- [x] Get the users location, the user must enable or decline this through location permissions 
- [x] If the user declines permission then a message must be shown to the user that this may affect functionality of the website
- [ ] If the user has initially declined location permissions either create some sort of way for them to be asked again or give them some directions to where they can enable this on their browser/system
