### ISSUE TITLE
User Story:Routing from user location to destination

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/Escape-and-explore#11]
**User Story:**
As a user, I would like to be able to see where destinations are in correlation to my current location

**Acceptance Criteria**
- [ ] The user must be able to see both their location and the chosen destination on the map
- [ ] Some sort of connection must be made between the two such as a line connecting them or actual directions of travelling to that location via real world routes
- [ ] An error message must be shown if any of the prerequisites such as user location or destination has not been selected or enabled

**Tasks**
- [ ] Enable the user to toggle/enable routing between themselves and the currently chosen destination
- [ ] Using googles maps routes API functionality enable the routing of the current user location to the destination
- [ ] If a current destination has not been chosen display an error message that the user must first select a destination
- [ ] If the user has declined permissions display an error message that the user must first enable this
