### ISSUE TITLE
User Story:Add Google maps API

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/Escape-and-explore#2]
**User Story:**
As a website user, I would like to be able to see my selected city on a map so I can understand the distance travelled and choose if it is right for me

**Acceptance Criteria**
- [x] A map must be displayed showing the destination
- [x] A marker must be placed at the destination

**Tasks**
- [x] Create a google maps API Key
- [x] Connect to the Google maps API
- [x] Create the code to display the google maps
- [x] Create the code to display a marker on the location of the destination
