### ISSUE TITLE
User Story:Destination images and descriptions

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/Escape-and-explore#3]
**User Story:**
As a website user, I would like to be able to get an insight of my potential destinations 
through images, descriptions and understanding where I have to travel

**Acceptance Criteria**
- [x] Images of the city must be displayed along with descriptions

**Tasks**
- [x] On selection of a city Images must appear(Fadein and Fadeout might be good)
- [x] On selection of a city descriptions must appear
