### ISSUE TITLE
User Story:Add recommended places

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/Escape-and-explore#4]
**User Story:**
As a young adult, I would like to have a display of recommended places to visit in each
destination to help me to cater each holiday to my own needs

**Acceptance Criteria**
- [x] Atleast a few destinations must be displayed by 
- [x] Links for partners should be placed in some if not all destinations

**Tasks**
- [x] Display places to visit in each recommended city
- [x] Place descriptions, links and potentially partners
