### ISSUE TITLE
User Story:Activity section

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/Escape-and-explore#5]
**User Story:**
As a parent, I would like to be able to have a selection of activities for my children and I so we can spend some family time together

**Acceptance Criteria**
- [ ] An activity section must be present in the website 
- [ ] Activities must be displayed with descriptions

**Tasks**
- [ ] Create a separate activity section OR Create a toggleable section for activities which would replace the destination images and descriptions, you should also be be able to toggle back
- [ ] Add descriptions and relvant links/partners
