### ISSUE TITLE
User Story:Expense calculator

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/Escape-and-explore#6]
**User Story:**
As a busy parent, strapped for cash I would like to be able to see the potential costs
incurred for activities or visits

**Acceptance Criteria**
- [ ] All selected activities must display an average cost and add this onto the estimated total
- [ ] The total must be displayed on the page(probably in one of the corners)
- [ ] A separate page or modal can popup to show all selected activities, destinations etc OR a list can be shown somewhere on the website with added items

**Tasks**
- [ ] Display avg. costs of each activity/destination in the appropriate area(where the activities are)
- [ ] Display the totals in one of the corners
- [ ] Make the total clickable, this should show a modal or lead to a new page OR open up a drop down list on the current page
