### ISSUE TITLE
User Story:Newsletter

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/Escape-and-explore#7]
**User Story:**
As a user, I would like to be able to signup for a newsletter so that I can see updated deals and new holiday destinations

**Acceptance Criteria**
- [ ] Somewhere on the age, likely at the bottom a form must be present to fill out for a newsletter
- [ ] The form must provide feedback if not filled out correctly
- [ ] The form must provide feedback in the form of a modal or other methods to show success if filled out correctly

**Tasks**
- [ ] Create a form to fillout for a newsletter
- [ ] Look at API's which can send out an email if feasible use to send out the email
- [ ] If incorrect inputs are entered display this with error messages
- [ ] If form is filled out correctly create a success page or modal to display following this
