### ISSUE TITLE
User Story:CTA Button

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/Escape-and-explore#8]
**User Story:**
As a user, I would like to be able to easily navigate to the booking area where I can create 
and finalise my next holiday plan

**Acceptance Criteria**
- [x] A call to action button must be present on the page, be very visible and easy to access from anywhere in the site

**Tasks**
- [x] Create a call to action button on the nav bar
- [x] Ensure the call to action button is very visible and stands out from other elements on the site
- [x] Ensure that the call to action button is always visible no matter where the user is on the site
