### ISSUE TITLE
User Story:Save cities/activities/places to visit

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/Escape-and-explore#9]
**User Story:**
As a user, I would like to save holiday destinations so I can come back to them at
another time

**Acceptance Criteria**
- [ ] Users must be able to save destinations they like
- [ ] Saved destinations must be accessible from somewhere within the same page or on another page
- [ ] This can be connected in one way or another to the calculate costs components of the site
- [ ] Activities/places to visit in each city must be displayed just so, as a part of the deal of the holiday in that city

**Tasks**
- [ ] Create some sort of indicator on the city destination images that can be toggled to save or unsave
- [ ] Create some sort of list, which can be opened from the main site and will display saved destinations
- [ ] Create some sort of indicator on the activities/places to visit portions of the site which can be toggled to add to the saved list
- [ ] Ensure the activities/places in each city is added as a part of a list/package of that city, not separated
